/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smsystem;

/**
 *
 * @author Prince Ranjan
 */
public class Age_criteria extends javax.swing.JFrame {

    /**
     * Creates new form Age_criteria
     */
    public Age_criteria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        b = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c1.setBackground(new java.awt.Color(255, 102, 102));
        c1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        c1.setForeground(new java.awt.Color(0, 0, 255));
        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX-X" }));
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 193, 36));

        ta.setEditable(false);
        ta.setBackground(new java.awt.Color(255, 153, 153));
        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Californian FB", 3, 24)); // NOI18N
        ta.setForeground(new java.awt.Color(0, 0, 255));
        ta.setLineWrap(true);
        ta.setRows(5);
        ta.setWrapStyleWord(true);
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 510, 140));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 130, 31));

        b.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        b.setForeground(new java.awt.Color(255, 51, 51));
        b.setText("CLEAR");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 130, 31));

        jLabel1.setFont(new java.awt.Font("Tunga", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGE CRITERIA...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 406, 71));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smsystem/f.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smsystem/Back_button.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smsystem/Age_criteria.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String c=(String)c1.getSelectedItem();
        if (c.equalsIgnoreCase("I"))
        {   b.doClick();
            ta.append("MINIMUM AGE OF STUDENT MUST BE 5 YEARS ");}
        if (c.equalsIgnoreCase("II"))
        {  b.doClick();
            ta.append("MINIMUM AGE OF STUDENT MUST BE 6 YEARS ");}
        if (c.equalsIgnoreCase("III"))
        {    b.doClick();
            ta.append("MINIMUM AGE OF STUDENT MUST BE 7 YEARS ");}
        if (c.equalsIgnoreCase("IV"))
        {    b.doClick();
            ta.append("MINIMUM AGE OF STUDENT MUST BE 8 YEARS ");}
        if (c.equalsIgnoreCase("V"))
        {    b.doClick();
            ta.append("MINIMUM AGE OF STUDENT MUST BE 9 YEARS ");}
        if (c.equalsIgnoreCase("VI"))
        {    b.doClick();
            ta.append("MINIMUM AGE OF STUDENT MUST BE 10 YEARS ");}
        if (c.equalsIgnoreCase("VII"))
        {    b.doClick();
            ta.append("MINIMUM AGE OF STUDENT MUST BE 11 YEARS ");}
        if (c.equalsIgnoreCase("VIII"))
        {    b.doClick();
            ta.append("MINIMUM AGE OF STUDENT MUST BE 12 YEARS ");}
        if (c.equalsIgnoreCase("IX-X"))
        {    b.doClick();
            ta.append("MINIMUM AGE OF STUDENT MUST BE 13-14 YEARS ");}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
        ta.setText("");
    }//GEN-LAST:event_bActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Marks_for_admission().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Subjects_offered().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Age_criteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Age_criteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Age_criteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Age_criteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Age_criteria().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b;
    private javax.swing.JComboBox c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
