/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package smsystem;

/**
 *
 * @author Prince Ranjan
 */
public class School_faculty extends javax.swing.JFrame {

    /**
     * Creates new form School_faculty
     */
    public School_faculty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_teacher_management = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_teachers = new javax.swing.JButton();
        txt_Employee = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_teachers1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_teacher_management.setBackground(new java.awt.Color(0, 204, 204));
        txt_teacher_management.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_teacher_management.setForeground(new java.awt.Color(0, 0, 255));
        txt_teacher_management.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smsystem/teacher.png"))); // NOI18N
        txt_teacher_management.setText("Tearchers");
        txt_teacher_management.setToolTipText("Tearcher Management Option-1");
        txt_teacher_management.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txt_teacher_managementAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(txt_teacher_management, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smsystem/employee.png"))); // NOI18N
        jLabel2.setText("Employees");
        jLabel2.setToolTipText("Employee Management Option-3");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        txt_teachers.setBackground(new java.awt.Color(255, 255, 255));
        txt_teachers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_teachers.setForeground(new java.awt.Color(0, 51, 51));
        txt_teachers.setText("Teachers");
        txt_teachers.setToolTipText("Teachers Data Entry Option");
        txt_teachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_teachersActionPerformed(evt);
            }
        });
        getContentPane().add(txt_teachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        txt_Employee.setBackground(new java.awt.Color(255, 255, 255));
        txt_Employee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Employee.setForeground(new java.awt.Color(51, 51, 51));
        txt_Employee.setText("Employees");
        txt_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Footlight MT Light", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setText("School faculty..");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 306, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smsystem/student.png"))); // NOI18N
        jLabel1.setText("Students");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        txt_teachers1.setBackground(new java.awt.Color(255, 255, 255));
        txt_teachers1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_teachers1.setForeground(new java.awt.Color(0, 51, 51));
        txt_teachers1.setText("Students");
        txt_teachers1.setToolTipText("Teachers Data Entry Option");
        txt_teachers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_teachers1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_teachers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smsystem/f.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smsystem/Back_button.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smsystem/School_faculty.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_teacher_managementAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txt_teacher_managementAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_teacher_managementAncestorAdded

    private void txt_teachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_teachersActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Teacher_Information().setVisible(true);
        
    }//GEN-LAST:event_txt_teachersActionPerformed

    private void txt_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmployeeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Employee_information().setVisible(true);
    }//GEN-LAST:event_txt_EmployeeActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:   
    }//GEN-LAST:event_jLabel7MouseClicked

    private void txt_teachers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_teachers1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Student_information().setVisible(true);
    }//GEN-LAST:event_txt_teachers1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Teacher_Information().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Contents().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(School_faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(School_faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(School_faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(School_faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new School_faculty().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton txt_Employee;
    private javax.swing.JLabel txt_teacher_management;
    private javax.swing.JButton txt_teachers;
    private javax.swing.JButton txt_teachers1;
    // End of variables declaration//GEN-END:variables
}
